theme: jekyll-theme-hacker

title: eslintcc
description: ESLint - JavaScript Complexity of Code

github:
  repository_url: https://github.com/eslintcc/eslintcc

google_analytics: 'UA-151934261-1'
yandex_metrika: 56156524