theme: jekyll-theme-hacker

title: eslintcc
description: ESLintCC is a ECMAScript/JavaScript/TypeScript tool that computes complexity of code by using ESLint

github:
  repository_url: https://github.com/eslintcc/eslintcc

google_analytics: 'UA-151934261-1'
yandex_metrika: 56156524